### ISSUE TITLE
sh4

### ISSUE THREAD

**Issue by Power535** [lxdream/lxdream#2]
Support sh4 platform on Linux ?
For compile

**Comment by nkeynes** [comment]
As in, host lxdream itself on sh-linux? It should be possible to build it (but will be interpreter-only)

**Comment by Power535** [comment]
Sorry , I do not understand
Possible compile and run  lxdream on board sh4 ?
I want try lxdream on board sh4 450 Mhz kernel 2.6
Thank you

**Comment by nkeynes** [comment]
You can certainly try it out, but I wouldn't expect it to be very fast. 
Closing as I don't think there's anything to do here?
